### ISSUE TITLE
Damaged TSEEQ.Documentation.pdf ?

### ISSUE THREAD

**Issue by PlexPro** [qlikperf/TSEEQ#1]
I have downloaded "TSEEQ-master.zip" twice, and for both downloads upon attempting to open "TSEEQ Documentation.pdf", whether from the extracted contents, or directly from within the zip file, I get this message from Adobe Reader:

"There was an error opening this document.  The file is damaged and could not be repaired."

René V.

[TSEEQ Documentation.pdf](https://github.com/qlikperf/TSEEQ/files/1623368/TSEEQ.Documentation.pdf)

**Comment by qlikperf** [comment]
Hi Rene,
Thanks for your report.  I have modified .gitatttibutes such that it no longer replaces line ending character sequences in binary files.  The PDF can now be viewed.  This change applies both to the [master ZIP file](https://github.com/qlikperf/TSEEQ/archive/master.zip) and the new [v3.1.1c release Zip file](https://github.com/qlikperf/TSEEQ/archive/v3.1.1c.zip). The direct link to the current, view-able PDF is now https://github.com/qlikperf/TSEEQ/blob/master/TSEEQ%20Documentation.pdf.
