### ISSUE TITLE
Missing "add-on" folder

### ISSUE THREAD

**Issue by ferdmanp** [qlikperf/TSEEQ#4]
During data load got message "QCEE Incremental1 add-on for TSEEQ was not found. "
Found out, that files "QCEE Incremental1.txt" and "QCEE Incremental2.txt" should be placed in $(vCommonScriptPath)\eee\add-ons\ directory, but "add-ons" directory doesn't exists in installation. Maybe it missed? Thanks

**Comment by qlikperf** [comment]
Hi ferdmanp,

Could you please email to me the _SaleforceExtractRules.xls_ file that you are using so that I can assist? My email addresses are on the first page of the Open Source Dashboard for Salesforce Documentation.pdf.

Thanks,

J. R.

**Comment by ferdmanp** [comment]
Done
